# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print(np.__version__)   # version
print(np.show_config())   # configuration

1.22.4
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS

#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
array1 = np.zeros(10)

#### 4. How to find the memory size of any array (★☆☆)

In [4]:
print(array1.size*array1.itemsize)

80


#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [5]:
array2 = np.zeros(10)
array2[4] = 1
print(array2)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)

In [6]:
a = np.arange(10,50)

#### 7. Reverse a vector (first element becomes last) (★☆☆)

In [7]:
a[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [8]:
b = np.arange(9).reshape(3,3)

#### 9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [9]:
c = np.array([1,2,0,0,4,0])
np.nonzero(c)

(array([0, 1, 4]),)

#### 10. Create a 3x3 identity matrix (★☆☆)
Hint : identity & eye, try to use 'help' to learn how to use two functions of numpy

In [10]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 11. Create a 3x3x3 array with random values (★☆☆)
Hint : numpy.random.random

In [12]:
elev = np.random.random((3,3,3))

#### 12. Create a 10x10 array with random values and find the **min**imum and **max**imum values (★☆☆)

In [13]:
twelv = np.random.random((10,10))
print(np.max(twelv))
print(np.min(twelv))

0.989978099705864
0.007391210950562277


#### 13. Create a random vector of size 30 and find the **mean** value (★☆☆)

In [14]:
thirt = np.random.random(30)
print(np.mean(thirt))

0.5078317079022536


#### 14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [15]:
fourt = np.ones((5,5))
fourt[1:-1,1:-1] = 0
print(fourt)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 15. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

nan
False
False
nan
True
False    # 오차 발생하니깐

#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the **diag**onal (★☆☆)

In [17]:
sixt = np.diag(1+np.arange(4), k = -1)
sixt

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [18]:
sevent = np.ones((8,8))
for i in range(8):
  for j in range(8):
    if (i+j)%2 == 0:
      sevent[i,j] = 0

print(sevent)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [19]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
Hint : use 'numpy.unravel_index(value, (x, y, z))

In [ ]:
eightt = np.arange(6*7*8).reshape(6,7,8)
np.unravel_index(99,(6,7,8))

(1, 5, 3)

#### 19. Normalize a 5x5 random matrix (★☆☆)
Hint : $Z = \frac{X - \overline{X}}{S}$

In [ ]:
ninet = np.random.random((5,5))
xbar = np.mean(ninet)
s = np.std(ninet)
ans = (ninet-xbar) / s
ans

array([[-1.05833693,  0.68169963, -0.40390474,  0.69980785,  1.32308451],
       [-0.19359309,  0.85061591,  0.03465493,  0.36215456, -1.4452792 ],
       [-1.61616208,  0.07867972, -1.67238046, -1.43659542, -1.15703227],
       [-0.17320689,  0.24068704, -0.46690861,  0.20507486,  0.7378101 ],
       [ 1.11676183,  1.55119296, -0.8119356 ,  0.66505118,  1.88806022]])

#### 20. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
Hint : modify the code below
```python
numpy.dtype([(value, numpy.ubyte), … , (value, numpy.ubyte)])
```

In [ ]:
np.dtype([('r',np.ubyte),('g',np.ubyte),('b',np.ubyte),('a',np.ubyte)])

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
a = np.arange(5*3).reshape(5,3)
b = np.arange(3*2).reshape(3,2)
np.dot(a,b)

array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
ans = np.arange(11)
ans[(3 <= ans) & (ans <= 8)] *= -1
print(ans)

[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]


#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
from numpy import *
print(sum(range(5),-1))   # axis == -1의 의미

10


#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
# 1j : 복소수

# 마지막 것만 성립하지 않음

3j

#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
np.array(0) / np.array(0)   # 나누기기

<ipython-input-68-3585dcb7ab9b>:1: RuntimeWarning: invalid value encountered in true_divide
  np.array(0) / np.array(0)


nan

In [ ]:
np.array(0) // np.array(0)   # 몫

<ipython-input-69-4764261090d0>:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


0

In [ ]:
np.array([np.nan]).astype(int).astype(float)

array([-9.22337204e+18])

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

In [20]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))    #np.intersect1d : 두 배열의 교집합을 정렬해서 배열열

[1 2 3 5]


#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [21]:
np.sqrt(-1) == np.emath.sqrt(-1)    #np.emath.sqrt(-1)은 1j로 표시되어 변수를 더 수학적으로 표현함 -> False

<ipython-input-21-16339fbc685e>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

In [22]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

In [23]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)       # A+B의 결과를 B에 할당해놓음
np.divide(A,2,out=A)    # A/2의 결과를 A에 할당
np.negative(A,out=A)    # -(A/2)를 A에 할당
np.multiply(A,B,out=A)  # (A+B)*(-A/2)와 같은 결과
print(A)

[-1.5 -1.5 -1.5]


#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

In [24]:
z = np.random.uniform(0,10,10)    # 양수의 무작위 원소 배열
print(z-z%1)          # z - z의 소수부분
print(z // 1)         # z의 정수부분
print(np.floor(z))    # z의 소수부분 버림
print(np.ceil(z))     # z의 소수부분 버림
print(z.astype(int))  # z를 정수로 변환
print(np.trunc(z))    # z의 소수부분 버림림

[0. 9. 6. 3. 2. 4. 3. 9. 5. 4.]
[0. 9. 6. 3. 2. 4. 3. 9. 5. 4.]
[0. 9. 6. 3. 2. 4. 3. 9. 5. 4.]
[ 1. 10.  7.  4.  3.  5.  4. 10.  6.  5.]
[0 9 6 3 2 4 3 9 5 4]
[0. 9. 6. 3. 2. 4. 3. 9. 5. 4.]


#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [26]:
z = np.zeros((5,5))   # 5*5개의 0
z += np.arange(5)     # 0에 0~4 각각 더해주기
print(z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 32. Create a random vector of size 10 and sort it (★★☆)

In [27]:
z = np.random.random(10)
np.sort(z)

array([0.02042709, 0.10713195, 0.12952867, 0.16756258, 0.37110091,
       0.45085345, 0.48597268, 0.49522417, 0.55718524, 0.72675138])

#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

In [28]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
np.array_equal(A,B)   # np.array_equal(a,b) : a,b 두 배열이 같은지 확인가능능

False

#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

In [29]:
z = np.random.random((10,2))
x, y = z[:,0],z[:,1]    #x와 y에 각각 0열, 1열 할당
r = np.sqrt(x**2+y**2)  # 데카르트 좌표로 표현
p = np.arctan2(y,x)     # 극좌표계 표현
print(r)
print(p)

[0.83454597 1.11492114 1.19084522 1.13609601 0.35678091 0.70781646
 0.46476701 0.64782862 0.96695892 0.44271056]
[0.75313971 0.83239489 0.8428413  0.6209872  1.23077978 0.79696518
 0.47120116 0.10890164 1.06018512 0.30073271]


#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

In [31]:
Z = np.random.random(10)
Z[Z.argmax()] = 0   #np.argmax()로 해당위치(인덱스)를 찾을 수 있음
print(Z)

[0.80533929 0.79738406 0.42341177 0.76448854 0.28587086 0.39074874
 0.         0.56345473 0.16868897 0.61152403]


#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

In [37]:
Z = np.arange(100)
v = np.random.uniform(0,100)
i = np.abs((Z-v)).argmin()          # 주어진 값에서 가장 가까운 값 찾기
print('인덱스:', i ,'/값:', Z[i])   # 가장 가까운값의 인덱스와 그 값 출력

인덱스: 31 /값: 31


#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

In [39]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [40]:
Z = np.arange(9).reshape(3,3)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

In [50]:
n = 10
p = 2
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),5)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 5. 0. 0. 0. 0. 0.]]


In [ ]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [ ]:
# column 1

In [62]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,0].argsort()])   # z[z[:,1].argsort()] 는 행의 첫번째(인덱스 0) 성분을 기준으로 정렬한다는 뜻

[[5 4 4]
 [7 5 7]
 [5 6 3]]
[[5 4 4]
 [5 6 3]
 [7 5 7]]


In [68]:
# column 2
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[6 6 1]
 [7 5 7]
 [8 8 4]]
[[7 5 7]
 [6 6 1]
 [8 8 4]]


In [67]:
# column 3
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,2].argsort()])

[[6 4 2]
 [4 3 6]
 [0 7 6]]
[[6 4 2]
 [4 3 6]
 [0 7 6]]
